version: '3'
services:
    db:
        build: ./db
        environment:
            MYSQL_DATABASE: demo
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_USER: mysql
            MYSQL_PASSWORD: 123
            DATABASE_HOST: db
        volumes:
            - ./mysql_data:/var/lib/mysql
    api:
        build: ./api
        environment:
            DATABASE_HOST: db
            MYSQL_PORT: 3306
            MYSQL_DATABASE: demo
            MYSQL_USER: mysql
            MYSQL_PASSWORD: 123
        ports:
            - "666:3000"
        depends_on:
            - db
        restart: on-failure 

